trigger:
- main

pool: mycomputeragent

stages: 
- stage: Build
  jobs:
  - job: FirstJob
    steps: 
    - bash: echo Job1-Hello, world 1!
  - job: SecondJob
    steps: 
    - bash: echo Job1-Hello, world 2!
- stage: DevDeploy
  jobs:
  - job: DevDeployJob
    steps: 
    - bash: echo BJob1-Hello, world 3 !
- stage: QADeploy
  jobs:
  - job: QADeployJob
    steps: 
    - bash: echo Job1-Hello, world 4!
- stage: ProdDeploy
  jobs:
  - job: PRODDeployJob
    steps: 
    - bash: echo Job1-Hello, world 4!

