trigger:
- main

pool: mycomputeragent

stages: 
- stage: Build
  jobs:
  - job: FirstJob
    steps: 
    - script: echo Job1-Hello, world!
  - job: SecondJob
    steps: 
    - script: echo Job1-Hello, world!
- stage: DevDeploy
  jobs:
  - job: DevDeployJob
    steps: 
    - script: echo Job1-Hello, world!
- stage: QADeploy
  jobs:
  - job: QADeployJob
    steps: 
    - script: echo Job1-Hello, world!
- stage: ProdDeploy
  jobs:
  - job: PRODDeployJob
    steps: 
    - script: echo Job1-Hello, world!

